[kube_master]
k8s-master-01 ansible_host=111.88.246.194 kube_internal_ip=10.20.10.31

[kube_workers]
k8s-worker-01 ansible_host=51.250.20.241 kube_internal_ip=10.20.20.17
k8s-worker-02 ansible_host=84.252.135.237 kube_internal_ip=10.20.30.7

[kubernetes:children]
kube_master
kube_workers

[all:vars]
ansible_user=teplov
ansible_ssh_private_key_file=/home/teplov/.ssh/id_github_no_pass
ansible_python_interpreter=/usr/bin/python3
