[kube_master]
k8s-master-01 ansible_host=158.160.48.17 ansible_user=teplov

[kube_workers]
k8s-worker-01 ansible_host=111.88.146.167 ansible_user=teplov
k8s-worker-02 ansible_host=158.160.220.27 ansible_user=teplov

[kubernetes:children]
kube_master
kube_workers

[kubernetes:vars]
ansible_ssh_private_key_file=~/.ssh/id_github_no_pass
