---
- name: Initialize Kubernetes master
  hosts: kube_master
  become: true

  tasks:
    - name: Detect master internal IP
      set_fact:
        kube_apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"

    - name: Show master internal IP
      debug:
        msg: "Kubernetes API server will advertise on {{ kube_apiserver_advertise_address }}"

    - name: Initialize cluster
      command: >
        kubeadm init
        --apiserver-advertise-address={{ kube_apiserver_advertise_address }}
        --pod-network-cidr=192.168.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kube config directory
      become_user: teplov
      file:
        path: /home/teplov/.kube
        state: directory
        mode: '0755'

    - name: Copy admin kubeconfig
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/teplov/.kube/config
        remote_src: yes
        owner: teplov
        group: teplov
        mode: '0600'
