name: Docker Build and Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: crp6gcfckbknlsc51u2f
  IMAGE_NAME: diplom-app

jobs:
  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_TOKEN }}" | docker login \
            --username iam \
            --password-stdin \
            cr.yandex


      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${{ github.sha }} \
            ./app


      - name: Push Docker image
        run: |
          docker push \
            $REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${{ github.sha }}


      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/diplom-app \
          diplom-app=$REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${{ github.sha }}

          kubectl rollout status deployment/diplom-app
