name: Terraform CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TF_IN_AUTOMATION: "true"
  YC_TOKEN: ${{ secrets.YC_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform version
        run: terraform version

      - name: Terraform init
        run: terraform init -input=false -no-color

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform plan
        run: terraform plan -input=false -no-color
